select PRODUCTION_PERIOD_START_DATE, Operator, sum(GAS_QUANTITY) as GAS_QUANTITY 
from [PA Production].dbo.OilGasProduction2022
WHERE GAS_QUANTITY <>0
Group by PRODUCTION_PERIOD_START_DATE, OPERATOR
Order by PRODUCTION_PERIOD_START_DATE, GAS_QUANTITY DESC
