--Query to populate top 5 producers per month
--Results populate multiple operators per month but i'm looking to only show top 5 distinct operators per month by total gas quantity

WITH CTE
AS
(
	SELECT PRODUCTION_PERIOD_START_DATE,
	OPERATOR,
	GAS_QUANTITY,
	ROW_NUMBER() over (PARTITION BY PRODUCTION_PERIOD_START_DATE ORDER BY SUM(GAS_QUANTITY) DESC) AS GAS_QUANTITY#
FROM [PA Production].dbo.OilGasProduction2022
GROUP BY PRODUCTION_PERIOD_START_DATE, OPERATOR, GAS_QUANTITY
)
SELECT PRODUCTION_PERIOD_START_DATE, OPERATOR, GAS_QUANTITY
FROM CTE
WHERE GAS_QUANTITY# <=5
ORDER BY PRODUCTION_PERIOD_START_DATE, GAS_QUANTITY#
